Repository iiitl/college-management, pull requests merged in 2023-04, with the labels that each got.

#7 Add Header Component
  client/src/components/homepage/header/Header.jsx
  client/src/components/homepage/header/Header.scss
  client/src/pages/home/Home.page.jsx
Labels: points - 10, points - 1

#15 #6 Completed: Updated The README.md File
  README.md
Labels: points - 3

#17 ISSUE #8 Added.
  design/Classroom_figma.md
Labels: points - 3

#22 ISSUE #1 - Added Footer of Home Page
  client/src/asset/svg/facebook.svg
  client/src/asset/svg/instagram.svg
  client/src/asset/svg/linkedin.svg
  client/src/asset/svg/twitter.svg
  client/src/components/homepage/footer/Footer.jsx
  client/src/components/homepage/footer/Footer.scss
  client/src/pages/home/Home.page.jsx
Labels: points - 1, points - 3

#27 Fixed #1 Homepage-- Call To Action
  client/src/components/homepage/callToAction/CallToAction.jsx
  client/src/components/homepage/callToAction/CallToAction.scss
  client/src/pages/home/Home.page.jsx
Labels: points - 5

#26 ISSUE #10 Added
  design/college_management_UI.md
Labels: points - 1, points - 3

#18 ISSUE #1 added homepage design file added
  design/Design_file_link.txt
  design/design_file.fig
Labels: points - 10

#29 #5 Made an Attendance Management system except the Leave Tab
  README.md
  client/index.html
  client/public/scholar.png
  client/src/app.jsx
  client/src/components/homepage/callToAction/CallToAction.scss
  client/src/pages/Attendance/Attendance.jsx
  client/src/pages/Attendance/AttendanceManagementSystem.css
  client/src/pages/Attendance/AttendanceManagementSystem.jsx
  client/src/pages/Attendance/AttendanceSystem.css
  client/src/pages/Attendance/AttendanceSystem.jsx
  client/src/pages/Attendance/Cal.css
  client/src/pages/Attendance/Hello.jsx
  client/src/pages/Attendance/Navbar.css
  client/src/pages/Attendance/Navbar.jsx
  client/src/pages/Attendance/hello.css
  client/src/pages/home/Home.page.jsx
  package-lock.json
  package.json
  yarn.lock
Labels: points - 10

#36 ISSUE #8 Add Student Classroom section
  client/src/components/notesManagement/student/Course.css
  client/src/components/notesManagement/student/class.css
  client/src/components/notesManagement/student/class.jsx
  client/src/components/notesManagement/student/course.jsx
  client/src/components/notesManagement/student/course_data.js
  client/src/pages/classroom/classroom.page.jsx
Labels: points - 10, points - 20

#37 #31: Made a Login/Sign Up Form
  client/index.html
  client/src/app.jsx
  client/src/components/homepage/LoginForm/Login.css
  client/src/components/homepage/LoginForm/Login.jsx
  client/src/components/homepage/callToAction/CallToAction.jsx
  client/src/components/homepage/callToAction/CallToAction.scss
  client/src/components/homepage/header/Header.jsx
  client/src/components/homepage/header/Header.scss
  client/src/pages/Attendance/AttendanceSystem.css
  client/src/pages/home/Home.page.jsx
Labels: points - 5, points - 1
